name: Generate Snake Animation

on:
  schedule: [{cron: "0 * * * *"}]
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  push:
    branches:
    - master
    
jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk@master
        with:
          github_user_name: xFGhoul
          svg_out_path: dist/github-contribution-grid-snake.svg
          gif_out_path: dist/github-snake.gif
